name: Backup Content

on:
  schedule:
    - cron: '0 2 * * *'  # Run at 2 AM daily
  workflow_dispatch:  # Allow manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Run Backup
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "wp db export - --path=/var/www/html" > backups/database/$(date +%Y%m%d).sql
          git config --global user.name "PAUSATF Backup Bot"
          git config --global user.email "noreply@pausatf.org"
          git add backups/database/
          git commit -m "Automated database backup $(date +%Y-%m-%d)"
          git push
